apiVersion: v1
kind: Namespace
metadata:
  name: dummy-message-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-message-service
  labels:
    app: dummy-message-service
    name: dummy-message-service
  namespace: dummy-message-service
spec:
  replicas: 1
  selector:
    matchLabels:
      name: dummy-message-service
  template:
    metadata:
      labels:
        name: dummy-message-service
    spec:
      containers:
        - name: dummy-message-service
          image: proman3419/dummy-message-service:latest
          imagePullPolicy: "IfNotPresent"
#          imagePullPolicy: "Always"
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
          ports:
            - containerPort: 8000
              name: http-web-svc
---
apiVersion: v1
kind: Service
metadata:
  name: dummy-message-service-svc
  namespace: dummy-message-service
spec:
  selector:
    name: dummy-message-service
  ports:
  - name: dummy-message-service-api-port
    protocol: TCP
    port: 8000
    targetPort: http-web-svc
# kubectl -n dummy-message-service port-forward svc/dummy-message-service-svc 8000:8000
