apiVersion: v1
kind: Namespace
metadata:
  name: dummy-message-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-message-service
  labels:
    app: dummy-message-service
    name: dummy-message-service
  namespace: dummy-message-service
spec:
  replicas: 1
  selector:
    matchLabels:
      name: dummy-message-service
  template:
    metadata:
      labels:
        name: dummy-message-service
    spec:
      containers:
        - name: dummy-message-service
          image: proman3419/dummy-message-service:latest
          imagePullPolicy: "IfNotPresent"
#          imagePullPolicy: "Always"
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
          ports:
            - containerPort: 8000
